KEYWORD_CATEGORIES = {
    # ── Food & Dining (Everyday, Professional, Gourmet) ──
    "swiggy": "Food & Dining", "zomato": "Food & Dining", "dominos": "Food & Dining", "domino": "Food & Dining", 
    "pizza": "Food & Dining", "restaurant": "Food & Dining", "chai": "Food & Dining", "tea": "Food & Dining", 
    "coffee": "Food & Dining", "lunch": "Food & Dining", "dinner": "Food & Dining", "breakfast": "Food & Dining", 
    "snack": "Food & Dining", "groceries": "Food & Dining", "grocery": "Food & Dining", "vegetables": "Food & Dining", 
    "barbeque": "Food & Dining", "bbq": "Food & Dining", "croissant": "Food & Dining", "bakery": "Food & Dining",
    "cafe": "Food & Dining", "dhaba": "Food & Dining", "biryani": "Food & Dining", "burger": "Food & Dining", 
    "maggi": "Food & Dining", "eat": "Food & Dining", "meal": "Food & Dining", "juice": "Food & Dining", 
    "milk": "Food & Dining", "bread": "Food & Dining", "hotel food": "Food & Dining", "tiffin": "Food & Dining",
    "pasta": "Food & Dining", "sushi": "Food & Dining", "taco": "Food & Dining", "nachos": "Food & Dining", 
    "ramen": "Food & Dining", "kebab": "Food & Dining", "steak": "Food & Dining", "pancake": "Food & Dining", 
    "waffle": "Food & Dining", "smoothie": "Food & Dining", "shake": "Food & Dining", "donut": "Food & Dining", 
    "muffin": "Food & Dining", "bagel": "Food & Dining", "curry": "Food & Dining", "rice": "Food & Dining", 
    "soup": "Food & Dining", "salad": "Food & Dining", "sandwich": "Food & Dining", "fries": "Food & Dining", 
    "wings": "Food & Dining", "nuggets": "Food & Dining", "brownie": "Food & Dining", "cookie": "Food & Dining", 
    "yogurt": "Food & Dining", "cereal": "Food & Dining", "popcorn": "Food & Dining", "chips": "Food & Dining", 
    "chocolate": "Food & Dining", "candy": "Food & Dining", "icecream": "Food & Dining", "boba": "Food & Dining", 
    "omelette": "Food & Dining", "bacon": "Food & Dining", "sausage": "Food & Dining", "biscuit": "Food & Dining", 
    "noodles": "Food & Dining", "puff": "Food & Dining", "tart": "Food & Dining", "pie": "Food & Dining", 
    "bun": "Food & Dining", "chicken": "Food & Dining", "beef": "Food & Dining", "mutton": "Food & Dining", 
    "prawns": "Food & Dining", "fish": "Food & Dining", "egg": "Food & Dining", "pav bhaji": "Food & Dining", 
    "chole bhature": "Food & Dining", "pani puri": "Food & Dining", "jalebi": "Food & Dining", "barfi": "Food & Dining", 
    "lassi": "Food & Dining", "falooda": "Food & Dining", "misal pav": "Food & Dining", "vada pav": "Food & Dining", 
    "appam": "Food & Dining", "pongal": "Food & Dining", "khichdi": "Food & Dining", "raita": "Food & Dining", 
    "papad": "Food & Dining", "pickle": "Food & Dining", "namkeen": "Food & Dining", "bhujia": "Food & Dining", 
    "petha": "Food & Dining", "modak": "Food & Dining", "kfc": "Food & Dining", "burger king": "Food & Dining", 
    "starbucks": "Food & Dining", "subway": "Food & Dining", "taco bell": "Food & Dining", "pizza hut": "Food & Dining", 
    "dunkin": "Food & Dining", "mcdonalds": "Food & Dining", "baskin robbins": "Food & Dining", 
    "chipotle": "Food & Dining", "pappa roti": "Food & Dining", "nandos": "Food & Dining",
    "curd": "Food & Dining", "paneer": "Food & Dining", "butter": "Food & Dining", "jam": "Food & Dining", 
    "honey": "Food & Dining", "rusk": "Food & Dining", "atta": "Food & Dining", "dal": "Food & Dining", 
    "oil": "Food & Dining", "sugar": "Food & Dining", "salt": "Food & Dining", "masala": "Food & Dining", 
    "chili": "Food & Dining", "turmeric": "Food & Dining", "peppar": "Food & Dining", "haldirams": "Food & Dining", 
    "bikanervala": "Food & Dining", "amul": "Food & Dining", "mother dairy": "Food & Dining", 
    "coke": "Food & Dining", "pepsi": "Food & Dining", "thums up": "Food & Dining", "sprite": "Food & Dining", 
    "maaza": "Food & Dining", "frooti": "Food & Dining", "real juice": "Food & Dining",
    "falafel": "Food & Dining", "hummus": "Food & Dining", "shawarma": "Food & Dining", "dumpling": "Food & Dining", 
    "momo": "Food & Dining", "spring roll": "Food & Dining", "rib": "Food & Dining", "brisket": "Food & Dining", 
    "scone": "Food & Dining", "macaron": "Food & Dining", "pretzel": "Food & Dining", "churro": "Food & Dining", 
    "fondue": "Food & Dining", "quiche": "Food & Dining", "crepe": "Food & Dining", "avocado": "Food & Dining", 
    "salmon": "Food & Dining", "kale": "Food & Dining", "quinoa": "Food & Dining", "tofu": "Food & Dining", 
    "tempeh": "Food & Dining", "chia": "Food & Dining", "granola": "Food & Dining", "espresso": "Food & Dining", 
    "cappuccino": "Food & Dining", "latte": "Food & Dining", "macchiato": "Food & Dining", "mocha": "Food & Dining", 
    "frappe": "Food & Dining", "kombucha": "Food & Dining", "matcha": "Food & Dining", "cider": "Food & Dining", 
    "ale": "Food & Dining", "lager": "Food & Dining", "stout": "Food & Dining", "pilsner": "Food & Dining", 
    "merlot": "Food & Dining", "chardonnay": "Food & Dining", "pinot": "Food & Dining", "sauvignon": "Food & Dining", 
    "cabernet": "Food & Dining", "prosecco": "Food & Dining", "champagne": "Food & Dining", "martini": "Food & Dining", 
    "margarita": "Food & Dining", "mojito": "Food & Dining", "negroni": "Food & Dining",

    # ── Transport (Global Airlines, Tech Parts, Services) ──
    "uber": "Transport", "ola": "Transport", "rapido": "Transport", "metro": "Transport", "bus": "Transport", 
    "petrol": "Transport", "fuel": "Transport", "auto": "Transport", "taxi": "Transport", "rickshaw": "Transport", 
    "cab": "Transport", "parking": "Transport", "toll": "Transport", "diesel": "Transport", 
    "bike service": "Transport", "car service": "Transport", "train ticket": "Transport", "indigo": "Transport", 
    "air india": "Transport", "vistara": "Transport", "spicejet": "Transport", "akasa": "Transport", 
    "emirates": "Transport", "qatar": "Transport", "lufthansa": "Transport", "delta": "Transport", 
    "united": "Transport", "ryanair": "Transport", "bolt": "Transport", "lyft": "Transport", "grab": "Transport", 
    "careem": "Transport", "yandex": "Transport", "lpg": "Transport", "cng": "Transport", "electric": "Transport", 
    "charging": "Transport", "ev": "Transport", "adblue": "Transport", "subway": "Transport", "tube": "Transport", 
    "tram": "Transport", "ferry": "Transport", "boat": "Transport", "e-rickshaw": "Transport", "shuttle": "Transport", 
    "volvo": "Transport", "sleeper": "Transport", "luxury bus": "Transport", "local train": "Transport", 
    "mono rail": "Transport", "puncture": "Transport", "tire": "Transport", "wheel": "Transport", 
    "oil change": "Transport", "coolant": "Transport", "alignment": "Transport", "washing": "Transport", 
    "spa": "Transport", "polish": "Transport", "tow": "Transport", "service": "Transport", "repair": "Transport", 
    "spare parts": "Transport", "helmet": "Transport", "bike rent": "Transport", "car rental": "Transport", 
    "zoomcar": "Transport", "revv": "Transport", "drivezy": "Transport", "vallet": "Transport", "road tax": "Transport", 
    "insurance": "Transport", "speed": "Transport", "parking fee": "Transport", "bridge": "Transport", 
    "tunnel": "Transport", "brake": "Transport", "clutch": "Transport", "battery charge": "Transport", 
    "car wash": "Transport", "detailing": "Transport", "wiper": "Transport", "headlight": "Transport",
    "challan": "Transport", "fine": "Transport", "tow charge": "Transport", "seat cover": "Transport",

    # ── Shopping & Lifestyle (E-commerce, Brands, Personal) ──
    "amazon": "Shopping", "flipkart": "Shopping", "myntra": "Shopping", "ajio": "Shopping", "nykaa": "Shopping", 
    "zara": "Shopping", "h&m": "Shopping", "nike": "Shopping", "adidas": "Shopping", "puma": "Shopping", 
    "reebok": "Shopping", "levi": "Shopping", "clothes": "Shopping", "shoes": "Shopping", "watch": "Shopping", 
    "perfume": "Shopping", "makeup": "Shopping", "skincare": "Shopping", "electronics": "Shopping", "laptop": "Shopping", 
    "mobile": "Shopping", "iphone": "Shopping", "samsung": "Shopping", "sony": "Shopping", "headphones": "Shopping", 
    "keyboard": "Shopping", "monitor": "Shopping", "mouse": "Shopping", "gaming": "Shopping", "ps5": "Shopping", 
    "xbox": "Shopping", "toys": "Shopping", "gifts": "Shopping", "jewelry": "Shopping", "bags": "Shopping", 
    "sunglasses": "Shopping", "home decor": "Shopping", "furniture": "Shopping", "ikea": "Shopping", 
    "pepperfry": "Shopping", "urban ladder": "Shopping", "lifestyle": "Shopping", "pantaloons": "Shopping", 
    "westside": "Shopping", "max": "Shopping", "trends": "Shopping", "shampoo": "Shopping", "soap": "Shopping", 
    "detergent": "Shopping", "tissue": "Shopping", "curtains": "Shopping", "bedsheet": "Shopping", 
    "towel": "Shopping", "umbrella": "Shopping", "raincoat": "Shopping", "winter wear": "Shopping", 
    "jacket": "Shopping", "hoodie": "Shopping", "jeans": "Shopping", "tshirt": "Shopping", "shirt": "Shopping", 
    "dress": "Shopping", "suit": "Shopping", "saree": "Shopping", "kurta": "Shopping", "fastrack": "Shopping", 
    "titan": "Shopping", "casio": "Shopping", "fossil": "Shopping", "apple": "Shopping", "oneplus": "Shopping", 
    "boat": "Shopping", "noise": "Shopping", "jbl": "Shopping", "bose": "Shopping", "marshall": "Shopping", 
    "canon": "Shopping", "nikon": "Shopping", "camera": "Shopping", "lens": "Shopping", "tripod": "Shopping", 
    "hard drive": "Shopping", "ssd": "Shopping", "ram": "Shopping", "gpu": "Shopping", "processor": "Shopping", 
    "tablet": "Shopping", "ipad": "Shopping", "kindle": "Shopping", "airpods": "Shopping", "smartwatch": "Shopping", 
    "fitbit": "Shopping", "garmin": "Shopping", "wallet": "Shopping", "belt": "Shopping", "tie": "Shopping", 
    "socks": "Shopping", "underwear": "Shopping", "pajamas": "Shopping", "shorts": "Shopping", 
    "activewear": "Shopping", "sneakers": "Shopping", "boots": "Shopping", "sandals": "Shopping", 
    "heels": "Shopping", "slippers": "Shopping", "handbag": "Shopping", "backpack": "Shopping", 
    "suitcase": "Shopping", "wallet": "Shopping", "earrings": "Shopping", "necklace": "Shopping", 
    "bracelet": "Shopping", "ring": "Shopping", "lipstick": "Shopping", "eyeliner": "Shopping", 
    "foundation": "Shopping", "mascara": "Shopping", "sunscreen": "Shopping", "moisturizer": "Shopping", 
    "face wash": "Shopping", "hair oil": "Shopping", "hair dryer": "Shopping", "trimmer": "Shopping", 
    "shaver": "Shopping", "epilator": "Shopping", "iron": "Shopping", "vacuum": "Shopping", 
    "air purifier": "Shopping", "humidifier": "Shopping", "kettle": "Shopping", "toaster": "Shopping", 
    "blender": "Shopping", "mixer": "Shopping", "fryer": "Shopping", "microwave": "Shopping", 
    "refrigerator": "Shopping", "washer": "Shopping", "dryer": "Shopping", "dishwasher": "Shopping", 
    "tv": "Shopping", "speaker": "Shopping", "projector": "Shopping", "lamp": "Shopping", 
    "clock": "Shopping", "mirror": "Shopping", "rug": "Shopping", "cushion": "Shopping", 
    "blanket": "Shopping", "pillow": "Shopping", "mattress": "Shopping", "shelf": "Shopping", 
    "desk": "Shopping", "chair": "Shopping", "sofa": "Shopping", "table": "Shopping",

    # ── Entertainment & Fun (Streaming, Gaming, Outings) ──
    "netflix": "Entertainment", "prime video": "Entertainment", "hotstar": "Entertainment", "disney": "Entertainment", 
    "youtube": "Entertainment", "spotify": "Entertainment", "apple music": "Entertainment", "audiobook": "Entertainment", 
    "kindle": "Entertainment", "audible": "Entertainment", "movies": "Entertainment", "cinema": "Entertainment", 
    "theater": "Entertainment", "pvr": "Entertainment", "inox": "Entertainment", "bookmyshow": "Entertainment", 
    "concert": "Entertainment", "festival": "Entertainment", "club": "Entertainment", "bar": "Entertainment", 
    "pub": "Entertainment", "gaming": "Entertainment", "steam": "Entertainment", "epic games": "Entertainment", 
    "playstation": "Entertainment", "nintendo": "Entertainment", "bowling": "Entertainment", "paintball": "Entertainment", 
    "amusement park": "Entertainment", "zoo": "Entertainment", "museum": "Entertainment", "art gallery": "Entertainment", 
    "subscriptions": "Entertainment", "membership": "Entertainment", "gym": "Entertainment", "sports": "Entertainment", 
    "football": "Entertainment", "cricket": "Entertainment", "tennis": "Entertainment", "badminton": "Entertainment", 
    "ipl": "Entertainment", "world cup": "Entertainment", "match ticket": "Entertainment", "stadium": "Entertainment", 
    "hulu": "Entertainment", "hbo": "Entertainment", "apple tv": "Entertainment", "sony liv": "Entertainment", 
    "zee5": "Entertainment", "voot": "Entertainment", "alt balaji": "Entertainment", "mubi": "Entertainment", 
    "crunchyroll": "Entertainment", "twitch": "Entertainment", "discord": "Entertainment", "patreon": "Entertainment", 
    "onlyfans": "Entertainment", "tinder": "Entertainment", "bumble": "Entertainment", "hinge": "Entertainment", 
    "grindr": "Entertainment", "okcupid": "Entertainment", "shaadi.com": "Entertainment", "matrimony": "Entertainment", 
    "karaoke": "Entertainment", "billiards": "Entertainment", "snooker": "Entertainment", "pool": "Entertainment", 
    "darts": "Entertainment", "board games": "Entertainment", "cards": "Entertainment", "casino": "Entertainment", 
    "gambling": "Entertainment", "betting": "Entertainment", "lottery": "Entertainment", "bingo": "Entertainment", 
    "arcade": "Entertainment", "vr": "Entertainment", "escape room": "Entertainment", "trampoline": "Entertainment", 
    "go kart": "Entertainment", "skating": "Entertainment", "skiing": "Entertainment", "surfing": "Entertainment", 
    "hiking": "Entertainment", "camping": "Entertainment", "trekking": "Entertainment", "rafting": "Entertainment", 
    "paragliding": "Entertainment", "skydiving": "Entertainment", "bungee": "Entertainment", "safari": "Entertainment", 
    "tour": "Entertainment", "sightseeing": "Entertainment", "guide": "Entertainment", "exhibition": "Entertainment", 
    "fair": "Entertainment", "circus": "Entertainment", "magic show": "Entertainment", "comedy": "Entertainment", 
    "standup": "Entertainment", "open mic": "Entertainment", "workshop": "Entertainment", "class": "Entertainment", 
    "dance": "Entertainment", "music lesson": "Entertainment", "instrument": "Entertainment", "hobby": "Entertainment",

    # ── Bills & Utilities (Monthly Must-haves) ──
    "rent": "Bills & Utilities", "electricity": "Bills & Utilities", "water bill": "Bills & Utilities", 
    "gas bill": "Bills & Utilities", "internet": "Bills & Utilities", "wifi": "Bills & Utilities", 
    "mobile recharge": "Bills & Utilities", "phone bill": "Bills & Utilities", "dth": "Bills & Utilities", 
    "maintenance": "Bills & Utilities", "society charges": "Bills & Utilities", "property tax": "Bills & Utilities", 
    "garbage": "Bills & Utilities", "newspaper": "Bills & Utilities", "milk delivery": "Bills & Utilities", 
    "maid": "Bills & Utilities", "cook": "Bills & Utilities", "driver salary": "Bills & Utilities", 
    "laundry": "Bills & Utilities", "dry cleaning": "Bills & Utilities", "broadband": "Bills & Utilities", 
    "postpaid": "Bills & Utilities", "prepaid": "Bills & Utilities", "recharge": "Bills & Utilities", 
    "cable": "Bills & Utilities", "utility": "Bills & Utilities", "sewer": "Bills & Utilities", 
    "security": "Bills & Utilities", "parking charges": "Bills & Utilities", "gym membership": "Bills & Utilities", 
    "club fees": "Bills & Utilities", "subscription": "Bills & Utilities", "insurance premium": "Bills & Utilities", 
    "health insurance": "Bills & Utilities", "life insurance": "Bills & Utilities", "car insurance": "Bills & Utilities", 
    "bike insurance": "Bills & Utilities", "loan emi": "Bills & Utilities", "mortgage": "Bills & Utilities", 
    "credit card bill": "Bills & Utilities", "education fees": "Bills & Utilities", "school fees": "Bills & Utilities", 
    "college fees": "Bills & Utilities", "tuition": "Bills & Utilities", "coaching": "Bills & Utilities", 
    "news": "Bills & Utilities", "magazine": "Bills & Utilities", "icloud": "Bills & Utilities", 
    "google one": "Bills & Utilities", "dropbox": "Bills & Utilities", "evernote": "Bills & Utilities", 
    "zoom": "Bills & Utilities", "slack": "Bills & Utilities", "microsoft 365": "Bills & Utilities", 
    "adobe": "Bills & Utilities", "canva": "Bills & Utilities", "hosting": "Bills & Utilities", 
    "domain": "Bills & Utilities", "vpn": "Bills & Utilities", "antivirus": "Bills & Utilities",

    # ── Healthcare (Medical & Wellness) ──
    "doctor": "Healthcare", "dentist": "Healthcare", "hospital": "Healthcare", "clinic": "Healthcare", 
    "pharmacy": "Healthcare", "medicine": "Healthcare", "medical": "Healthcare", "lab test": "Healthcare", 
    "blood test": "Healthcare", "x-ray": "Healthcare", "therapy": "Healthcare", "counseling": "Healthcare", 
    "psychologist": "Healthcare", "physician": "Healthcare", "surgeon": "Healthcare", "medication": "Healthcare", 
    "tablet": "Healthcare", "syrup": "Healthcare", "bandage": "Healthcare", "first aid": "Healthcare", 
    "mask": "Healthcare", "sanitizer": "Healthcare", "vitamin": "Healthcare", "protein": "Healthcare", 
    "supplement": "Healthcare", "gym": "Healthcare", "yoga": "Healthcare", "meditation": "Healthcare", 
    "spa": "Healthcare", "massage": "Healthcare", "salon": "Healthcare", "barber": "Healthcare", 
    "haircut": "Healthcare", "facial": "Healthcare", "pedicure": "Healthcare", "manicure": "Healthcare", 
    "wellness": "Healthcare", "optician": "Healthcare", "glasses": "Healthcare", "lenses": "Healthcare", 
    "checkup": "Healthcare", "scan": "Healthcare", "mri": "Healthcare", "ct scan": "Healthcare", 
    "ultrasound": "Healthcare", "vaccine": "Healthcare", "injection": "Healthcare", "ambulance": "Healthcare", 
    "nurse": "Healthcare", "caregiver": "Healthcare", "elderly care": "Healthcare", "baby care": "Healthcare", 
    "diaper": "Healthcare", "formula": "Healthcare", "pediatrician": "Healthcare", "gynecologist": "Healthcare", 
    "dermatologist": "Healthcare", "orthopedic": "Healthcare", "cardiologist": "Healthcare", 
    "neurologist": "Healthcare", "oncologist": "Healthcare", "ent": "Healthcare", "urologist": "Healthcare", 
    "psychiatrist": "Healthcare", "rehab": "Healthcare", "detox": "Healthcare", "herbal": "Healthcare", 
    "homeopathy": "Healthcare", "ayurveda": "Healthcare", "unani": "Healthcare", "acupuncture": "Healthcare", 
    "chiropractor": "Healthcare", "fertility": "Healthcare", "ivf": "Healthcare", "pregnancy": "Healthcare", 
    "delivery": "Healthcare", "dialysis": "Healthcare", "physiotherapy": "Healthcare", "crutches": "Healthcare", 
    "wheelchair": "Healthcare", "hearing aid": "Healthcare", "dentures": "Healthcare", "braces": "Healthcare", 
    "invisalign": "Healthcare", "ointment": "Healthcare", "cream": "Healthcare", "drops": "Healthcare", 
    "inhaler": "Healthcare", "insulin": "Healthcare", "test strips": "Healthcare", "thermometer": "Healthcare", 
    "bp monitor": "Healthcare", "oximeter": "Healthcare", "nebulizer": "Healthcare",

    # ── Education & Career (成長) ──
    "books": "Education", "stationery": "Education", "pen": "Education", "notebook": "Education", 
    "course": "Education", "certification": "Education", "exam fee": "Education", "workshop": "Education", 
    "seminar": "Education", "webinar": "Education", "training": "Education", "coaching": "Education", 
    "tutor": "Education", "bootcamp": "Education", "conference": "Education", "admission": "Education", 
    "library": "Education", "school": "Education", "college": "Education", "university": "Education", 
    "upskilling": "Education", "udemy": "Education", "coursera": "Education", "linkedin learning": "Education", 
    "skillshare": "Education", "edx": "Education", "masterclass": "Education", "pluralsight": "Education", 
    "brilliant": "Education", "duolingo": "Education", "languages": "Education", "music class": "Education", 
    "art class": "Education", "coding": "Education", "aws": "Education", "azure": "Education", 
    "google cloud": "Education", "terraform": "Education", "kubernetes": "Education", "docker": "Education", 
    "python": "Education", "javascript": "Education", "react": "Education", "angular": "Education", 
    "vue": "Education", "node": "Education", "java": "Education", "cpp": "Education", "swift": "Education", 
    "kotlin": "Education", "rust": "Education", "go": "Education", "sql": "Education", "nosql": "Education", 
    "data science": "Education", "ml": "Education", "ai": "Education", "design": "Education", 
    "ui/ux": "Education", "figma": "Education", "photoshop": "Education", "illustrator": "Education", 
    "video editing": "Education", "marketing": "Education", "seo": "Education", "ads": "Education", 
    "business": "Education", "mba": "Education", "finance": "Education", "trading": "Education", 
    "stocks": "Education", "crypto": "Education", "real estate": "Education", "law": "Education", 
    "medical school": "Education", "engineering": "Education", "phd": "Education", "research": "Education", 
    "journal": "Education", "thesis": "Education", "paper": "Education", "degree": "Education", 
    "diploma": "Education", "internship": "Education", "placement": "Education", "cv": "Education", 
    "resume": "Education", "interview": "Education", "portfolio": "Education", "networking": "Education",

    # ── Travel & Vacation (Exploration) ──
    "hotel": "Travel", "resort": "Travel", "airbnb": "Travel", "flight": "Travel", "airline": "Travel", 
    "train": "Travel", "railway": "Travel", "cruise": "Travel", "visa": "Travel", "passport": "Travel", 
    "sightseeing": "Travel", "tour": "Travel", "guide": "Travel", "souvenir": "Travel", "luggage": "Travel", 
    "travel insurance": "Travel", "forex": "Travel", "roaming": "Travel", "vacation": "Travel", "trip": "Travel", 
    "holiday": "Travel", "staycation": "Travel", "backpacking": "Travel", "hostel": "Travel", "homestay": "Travel", 
    "glamping": "Travel", "safari": "Travel", "trek": "Travel", "expedition": "Travel", "adventure": "Travel", 
    "map": "Travel", "lonely planet": "Travel", "tripadvisor": "Travel", "makemytrip": "Travel", 
    "goibibo": "Travel", "booking.com": "Travel", "agoda": "Travel", "expedia": "Travel", "kayak": "Travel", 
    "skyscanner": "Travel", "cleartrip": "Travel", "easemytrip": "Travel", "ixigo": "Travel", 
    "uber intercity": "Travel", "zoomcar": "Travel", "self drive": "Travel", "chauffeur": "Travel", 
    "road trip": "Travel", "toll": "Travel", "highway": "Travel", "airport": "Travel", "lounge": "Travel", 
    "duty free": "Travel", "check-in": "Travel", "boarding": "Travel", "itinerary": "Travel", 
    "museum ticket": "Travel", "monument": "Travel", "park": "Travel", "beach": "Travel", "mountain": "Travel", 
    "resort fee": "Travel", "tip": "Travel", "local transport": "Travel", "shuttle": "Travel",

    # ── Investments (Wealth Building) ──
    "stocks": "Investments", "shares": "Investments", "mutual funds": "Investments", "sip": "Investments", 
    "crypto": "Investments", "bitcoin": "Investments", "ethereum": "Investments", "gold": "Investments", 
    "silver": "Investments", "real estate": "Investments", "fd": "Investments", "rd": "Investments", 
    "ppf": "Investments", "nps": "Investments", "insurance": "Investments", "bonds": "Investments", 
    "dividend": "Investments", "trading": "Investments", "zerodha": "Investments", "groww": "Investments", 
    "upstox": "Investments", "etf": "Investments", "ipo": "Investments", "esop": "Investments", 
    "reit": "Investments", "commodity": "Investments", "forex": "Investments", "options": "Investments", 
    "futures": "Investments", "demat": "Investments", "brokerage": "Investments", "capital gains": "Investments", 
    "tax saving": "Investments", "elss": "Investments", "lic": "Investments", "pf": "Investments", 
    "epf": "Investments", "vpf": "Investments", "gratuity": "Investments", "pension": "Investments", 
    "smallcase": "Investments", "kuvera": "Investments", "indmoney": "Investments", "coinbase": "Investments", 
    "binance": "Investments", "wazirx": "Investments", "trent": "Investments", "reliance": "Investments", 
    "tata": "Investments", "hdfc": "Investments", "sbi": "Investments", "icici": "Investments", 
    "infosys": "Investments", "tcs": "Investments", "apple stock": "Investments", "tesla": "Investments", 
    "nvidia": "Investments", "google stock": "Investments", "amazon stock": "Investments", 
    "real estate deposit": "Investments", "token money": "Investments", "registration": "Investments", 
    "stamp duty": "Investments", "plot": "Investments", "flat": "Investments", "shop": "Investments", 
    "commercial": "Investments", "agriculture": "Investments", "jewellery": "Investments", 
    "bullion": "Investments", "coin": "Investments", "vault": "Investments", "locker": "Investments",

    # ── Other (Uncategorized or Unique) ──
    "gift": "Other", "donation": "Other", "charity": "Other", "temple": "Other", "church": "Other", 
    "mosque": "Other", "laundry": "Other", "cleaning": "Other", "pest control": "Other", "courier": "Other", 
    "shipping": "Other", "tax": "Other", "fine": "Other", "penalty": "Other", "court": "Other", 
    "legal": "Other", "notary": "Other", "wedding": "Other", "party": "Other", "event": "Other", 
    "funeral": "Other", "miscellaneous": "Other", "cash": "Other", "atm": "Other", "withdrawal": "Other", 
    "transfer": "Other", "repayment": "Other", "borrowed": "Other", "lent": "Other", "interest": "Other", 
    "fees": "Other", "commission": "Other", "brokerage": "Other", "refund": "Other", "reversal": "Other", 
    "adjustment": "Other", "correction": "Other", "unknown": "Other", "others": "Other", "miscel": "Other", 
    "etc": "Other", "pocket money": "Other", "allowance": "Other", "tip": "Other", "church": "Other", 
    "guru": "Other", "ngo": "Other", "relief": "Other", "fund": "Other", "trust": "Other", 
    "lost": "Other", "stolen": "Other", "fraud": "Other", "scam": "Other", "dispute": "Other", 
    "settlement": "Other", "claim": "Other", "compensation": "Other", "inheritance": "Other", 
    "alimony": "Other", "child support": "Other", "escrow": "Other", "bail": "Other", "pawn": "Other", 
    "guarantee": "Other", "warranty": "Other", "membership": "Other", "union": "Other", 
    "association": "Other", "license": "Other", "permit": "Other", "visa": "Other", "stay": "Other"
}
